### ISSUE TITLE
Checklist for Long-range Colloquium on 2020-06-24

### ISSUE THREAD

**Issue by giulia-pacchioni** [virtualscienceforum/virtualscienceforum#107]
- [x] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] software test with the speaker (up to -1 day)
- [x] creating polls for the talk (up to -1 day)
- [x] reminder twitter announcement (-3 days)
- [x] assign the roles (moderator/recording)
- [x] recheck capacity, scale up the room (-1 day)
- [x] close the registration and update the page (right after the talk)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording on YouTube and embed on webpage (+2 days)

**Comment by akhmerov** [comment]
@giulia-pacchioni did you hear back from the speaker?

**Comment by giulia-pacchioni** [comment]
Yes! He is happy with the recording, but would like to cut the questions because of the unpublished data he flashed during the question time.
