### ISSUE TITLE
Checklist for Long Range Colloquium on 2020-07-08

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#111]
- [X] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] software test with the speaker (up to -1 day)
- [x] creating polls for the talk (up to -1 day)
- [x] reminder twitter announcement (-1 day)
- [x] assign the roles (moderator/recording)
- [x] recheck capacity, scale up the room (-1 day)
- [x] close the registration and update the page (right after the talk)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording on YouTube and embed on webpage (+2 days)
