### ISSUE TITLE
Checklist for LRC on 2020-08-05

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#130]
- [x] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] Abstract updated
- [x] mailing list announcement (-1 week)
- [x] twitter announcement (-1 week)
- [x] software test with the speaker (up to -1 day)
- [x] reminder twitter announcement (-1 day)
- [x] assign the roles (moderator/recording)
- [x] close the registration and update the page (right after the talk)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording on YouTube and embed on webpage (+2 days)

**Comment by greplova** [comment]
speaker approval for the video granted
