### ISSUE TITLE
Checklist for LRC on August 19, 2020

### ISSUE THREAD

**Issue by babaks77** [virtualscienceforum/virtualscienceforum#132]
- [ ] registration open (-2 weeks)
- [ ] page updated (-2 weeks)
- [ ] email announcement to all who signed up for updates (-2 weeks)
- [ ] twitter announcement (-2 weeks)
- [ ] software test with the speaker (up to -1 day)
- [ ] creating polls for the talk (up to -1 day)
- [ ] reminder twitter announcement (-3 days)
- [ ] assign the roles (moderator/recording)
- [ ] recheck capacity, scale up the room (-1 day)
- [ ] close the registration and update the page (right after the talk)
- [ ] get the speaker's approval of the recording (+1 day)
- [ ] publish the recording on YouTube and embed on webpage (+2 days)
