### ISSUE TITLE
Checklist for Long Range Colloquium with Michel Devoret on Sept. 16

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#141]
- [x] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] Check if the speaker wants to join earlier for an informal chat (waiting to hear)
  - [x] Check if they do
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup)
- [x] A reminder email (-4 hours)
- [x] close the registration and update the page (right after the talk)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording on YouTube and embed on webpage (+2 days)

**Comment by vfatemi** [comment]
Awaiting title and abstract.

**Comment by vfatemi** [comment]
Michel will join the pre-seminar chat.

**Comment by vfatemi** [comment]
Michel is ok with the recording.

**Comment by babaks77** [comment]
I see the recording is waiting to be published to YouTube. Is there a technical reason for not having done so yet?

**Comment by akhmerov** [comment]
Sorry, more an attention reason. I got nerd sniped by trying to automate the processing and the rabbit hole was deeper than expected. If you have some time, please publish.
