### ISSUE TITLE
Checklist for LRC with Pedram Roushan on Sep 30, 2020

### ISSUE THREAD

**Issue by babaks77** [virtualscienceforum/virtualscienceforum#146]
- [x] Title / abstract
- [x] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup)
- [x] A reminder email (-4 hours)
- [x] close the registration and update the page (right after the talk)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording on YouTube and embed on webpage (+2 days)
