### ISSUE TITLE
Checklist for Brian Skinner Long Range Colloquium on October 14

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#168]
- [x] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup)
- [x] A reminder email (-4 hours)
- [x] close the registration and update the page (right after the talk)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording on YouTube and embed on webpage (+2 days)

**Comment by vfatemi** [comment]
Brian is ok with recording and publishing the talk.

**Comment by vfatemi** [comment]
Brian will join for the 15 minute chat.

**Comment by vfatemi** [comment]
Brian has approved the recording.

**Comment by akhmerov** [comment]
Can you also provide the timestamps for start and end times to trim the video?

**Comment by vfatemi** [comment]
current start is good.

we could trim the end a little bit, to 1:22:38

**Comment by akhmerov** [comment]
Did the upload, youtube video ID is 9P1iBFLPIZk

**Comment by vfatemi** [comment]
embedded the video on the LRC page. closing the issue now.
