### ISSUE TITLE
Checklist for Long Range Colloquium on 28-10-2020

### ISSUE THREAD

**Issue by greplova** [virtualscienceforum/virtualscienceforum#197]
- [x] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup)
- [x] A reminder email (-4 hours)
- [x] close the registration and update the page (right after the talk)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording on YouTube and embed on webpage (+2 days)

**Comment by akhmerov** [comment]
I scheduled the email announcement

**Comment by greplova** [comment]
permission to publish recording granted
