### ISSUE TITLE
Checklist for Long Range Colloquium on 2020-11-11 by Jennifer Cano

### ISSUE THREAD

**Issue by babaks77** [virtualscienceforum/virtualscienceforum#206]
- [x] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup)
- [x] A reminder email (-4 hours)
- [x] close the registration and update the page (right after the talk)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording on YouTube and embed on webpage (+2 days)

**Comment by akhmerov** [comment]
For a reference, here's the registration reminder email:

```
Dear %recipient_name%,

Thank you for registering for today's Long Range Colloquium by {speaker_name}! The talk will begin in three hours (19:30 CET / 2:30 PM EST).  
Pay attention to the time: because of the recent time zone switch, the talk is one hour later in the US time zones!

As usual, we will have an informal chat about research with {speaker_name} starting a bit earlier—15 minutes before the talk. You are very welcome to join!

Your can join using your [registration link](%recipient.join_url%).

The title and the abstract of the talk are below.

**Title:** {title}

**Abstract:** {abstract}

See you soon,  
The Virtual Science Forum team
```

**Comment by babaks77** [comment]
Here is a suggestion with reminder for breakout rooms:

```
Dear %recipient_name%,

Thank you for registering for today's Long Range Colloquium by {speaker_name}! The talk will begin in three hours (19:30 CET / 1:30 PM EST).

As usual, we will have an informal chat about research with {speaker_name} starting a bit earlier—15 minutes before the talk. You are very welcome to join! 

We will also introduce breakout chat rooms after the talk to continue discussions. You need to have installed the [latest Zoom client](https://zoom.us/download) to choose the rooms you'd like to join.

Your can join using your [registration link](%recipient.join_url%).

The title and the abstract of the talk are below.

**Title:** {title}

**Abstract:** {abstract}

See you soon,  
The Virtual Science Forum team
```

**Comment by akhmerov** [comment]
I propose:

> If you want to use this opportunity to catch up with a colleague after the talk, we will leave the meeting open after the talk and allow participants to chat in breakout rooms to continue discussions. You need the [latest Zoom client](https://zoom.us/download) to use this feature.

@babaks77 is that OK?

**Comment by babaks77** [comment]
Yes, that sounds good. Thanks!

**Comment by vfatemi** [comment]
Looks good.

**Comment by akhmerov** [comment]
@babaks77 did you get the approval for publishing the recording?

**Comment by babaks77** [comment]
No, I dropped the ball on this for a while. Picking it back up again now.
