### ISSUE TITLE
Checklist for LRC by Deji Akinwande on 2020-12-09

### ISSUE THREAD

**Issue by greplova** [virtualscienceforum/virtualscienceforum#246]
- [x] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup)
- [x] close the registration and update the page (right after the talk)
- [x] A reminder email (-4 hours)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording on YouTube and embed on webpage (+2 days)

**Comment by giulia-pacchioni** [comment]
Sorry but I don't understand how to update researchseminars.org. Is there a VSF account? Any advice @babaks77?

**Comment by akhmerov** [comment]
I see the talk is already [listed there](https://researchseminars.org/seminar/VSFLRC), but the title and abstract are still TBA. @babaks77 needs to either share access or edit the listing.

**Comment by giulia-pacchioni** [comment]
Indeed, it just needs updating.

**Comment by babaks77** [comment]
I have shared the password to access the RS account with @akhmerov and @giulia-pacchioni. It's under babaks+vsf@gmail.com. If others need access, let me know so I can share credentials.

**Comment by akhmerov** [comment]
Thanks. I think you can instead add managers to the event series.

**Comment by babaks77** [comment]
You're right, @akhmerov. I will add you and @giulia-pacchioni. I can add others as needed.

**Comment by giulia-pacchioni** [comment]
Thanks @babaks77 !
