### ISSUE TITLE
Checklist for LRC on 2021-01-20

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#278]
## Speaker name

Leonid Levitov

## Speaker affiliation

MIT

## Title

‌Electrons Bloch-waltzing in moire superlattices

## Abstract

A striking prediction of the quantum theory of solids is that Bloch electrons in the presence of a constant electric field oscillate at a frequency tunable by the field and taking identical values for all carriers in the band. As a paradigmatic example of collective electron dynamics, Bloch oscillations received much attention, and yet, achieving this regime in solids proved to be challenging. This talk will discuss the new ideas and a new hope triggered by the advent of van der Waals heterostructures, in particular the flat bands in Moire graphene. There are several interesting not-yet-explored regimes harbored by these systems. One is synchronous oscillations of “enlightened” electrons coupled to “the big power in the sky” (the EM field of a proximal resonator)—a collective many-body dynamics that holds promise for THz electronics. Another is magnetic Bloch oscillations achieved by combining constant electric and magnetic fields. The unique dynamical regimes arising in this case are described by the Ashcroft-Mermin (AM) Hamiltonian. We will demonstrate that the AM dynamics is integrable and identify two distinct phases, electric and magnetic, exhibiting position-momentum duality—the orbits extended in the $k$ space and confined in the $x$ space, and vice versa. The boundary between the electric and magnetic phases hosts an interesting and presently poorly understood chaotic dynamical phase. The two phases—electric and magnetic—are of keen interest both as examples of complex quantum dynamics arising in a simple setting and because of their relevance for THz research.

## Date

2021-01-20

## Checklist

- [ ] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [ ] Check if the speaker wants to join earlier for an informal chat
  - [ ] Check if they do
- [ ] email announcement to all who signed up for updates (-2 weeks)
- [ ] twitter announcement (-2 weeks)
- [ ] reminder twitter announcement (-2 days)
- [ ] assign the roles (moderator/backup) (-2 days)
- [ ] Email the speaker their login link (access it via Zoom UI)
- [ ] A reminder email (-4 hours)
- [ ] Relay to the speaker the video link and request approval of the recording publication.
- [ ] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"
