### ISSUE TITLE
Checklist for LRC on 2021-02-03

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#279]
## Speaker name

Andrea Young

## Speaker affiliation

UCSB

## Title

*TBA*

## Abstract

*TBA*

## Date

2021-02-03

## Checklist

- [ ] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [ ] Check if the speaker wants to join earlier for an informal chat
  - [ ] Check if they do
- [ ] email announcement to all who signed up for updates (-2 weeks)
- [ ] twitter announcement (-2 weeks)
- [ ] reminder twitter announcement (-2 days)
- [ ] assign the roles (moderator/backup) (-2 days)
- [ ] Email the speaker their login link (access it via Zoom UI)
- [ ] A reminder email (-4 hours)
- [ ] Relay to the speaker the video link and request approval of the recording publication.
- [ ] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by akhmerov** [comment]
@vfatemi please edit the issue description once you have the title and the abstract.

**Comment by akhmerov** [comment]
Thanks for the update, I'll do the announcement.

**Comment by vfatemi** [comment]
The speaker approves publishing the recording. start 00:00:00, end 01:25:21.

**Comment by akhmerov** [comment]
The speaker approves publishing the recording. start 00:00:00, end 01:25:21.
