### ISSUE TITLE
Checklist for LRC by Xie Chen on 2021-02-17

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#280]
## Speaker name

Xie Chen

## Speaker affiliation

Caltech

## Title

Fracton and Chern-Simons Theory

## Abstract

Fracton order describes the peculiar phenomena that point excitations in certain strongly interacting systems either cannot move at all or are only allowed to move in a lower dimensional sub-manifold. It has recently been discovered in various lattice models, tensor gauge theories, etc. In this talk, we discuss how another powerful field theory framework -- the 2+1D Chern-Simons (CS) gauge theory -- can be used to provide new insight and explore new possibilities in 3+1D fracton order. 2+1D U(1) gauge theories with a CS term provide a simple and complete characterization of 2+1D Abelian topological orders. To study 3+1D fracton order, we extend the theory by taking the number of component gauge fields to be infinity. In the simplest case of infinite-component CS gauge theory, different components do not couple to each other and the theory describes a decoupled stack of 2+1D fractional Quantum Hall systems with quasi-particles moving only in 2D planes -- hence a fractonic system. More interestingly, we find that when the component gauge fields do couple through the CS term, more varieties of fractonic orders are possible. For example, they may describe foliated fractonic systems which extends the framework found in exactly solvable models. Moreover, we find examples which lie beyond the foliation framework, characterized by 2D excitations of infinite order and braiding statistics that are not strictly local.

## Date

2021-02-17

## Checklist

- [x] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI)
- [x] A reminder email (-4 hours)
- [x] Relay to the speaker the video link and request approval of the recording publication.
- [x] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by akhmerov** [comment]
@everthemore copying here so that you won't overlook it in gitter. Emailing speaker the link is a manual task. You need to go to the  meeting settings → registrants → view → go to the very last one (that's the speaker), → copy link info.

**Comment by everthemore** [comment]
the speaker approves publishing the recording. start 00:00:09, end 01:12:52

**Comment by akhmerov** [comment]
approve publishing (nvm me, just triggering our bot)
