### ISSUE TITLE
Checklist for the first session

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#29]
- [x] program finalized
- [x] program posted on the website
- [x] moderator and the speaker selected
- [x] we informed the speakers about trying screensharing
- [x] zoom link posted on the website #30
- [x] confirmation email to registered participants (@akhmerov will send at 08:00 EST).
