### ISSUE TITLE
Checklist for LRC Monika Aidelsburger on 03-03-2021

### ISSUE THREAD

**Issue by greplova** [virtualscienceforum/virtualscienceforum#293]
## Speaker name
Monika Aidelsburger

## Speaker affiliation
Ludwig-Maximilians-University Munich

## Title

Ultracold atoms in optical lattices out-of-equilibrium

## Abstract

Well-controlled synthetic quantum systems, such as ultracold atoms in optical lattices, offer intriguing possibilities to study complex many-body problems relevant to a variety of research areas, ranging from condensed matter to high-energy physics. In particular, out-of-equilibrium phenomena constitute natural applications of quantum simulators, which have already successfully demonstrated simulations in regimes that are beyond reach using state-of-the-art numerical techniques.
This enables us to shed new light on fundamental questions about the thermalization of isolated quantum many-body systems. While generic models are expected to thermalize according to the eigenstate thermalization hypothesis (ETH), violation of ETH is believed to occur mainly in two types of systems: integrable models and many-body localized systems. In between these two extreme limits there is, however, a whole range of models that exhibit more complex dynamics, for instance, due to an emergent fragmentation of the Hilbert space into many dynamically disconnected subspaces. Here, we realize such a model by implementing the 1D Fermi-Hubbard model with a strong linear potential [1] and observe strong initial-state dependent thermalization - a smoking-gun signature of Hilbert-space fragmentation.
Engineering quantum systems out-of-equilibrium, on the other hand, further can be used as a tool to engineer novel quantum phases of matter, which cannot be accessed in static realizations. To this end, the system’s parameters are varied periodically, a method commonly known as Floquet engineering [2]. This facilitated the realization of paradigmatic topological lattice models and recently inspired ideas for implementing Z2 lattice gauge theories [3]. The rich properties of topological Floquet systems, however, transcend those of their static counterparts, resulting in a generalized bulk-edge correspondence. As a consequence, topological edge modes can exist even in situations where the bulk bands have zero Chern numbers. The novel properties of such anomalous Floquet systems open the door to exciting new non- equilibrium many-body phases without any static analogue [4].

[1] S. Scherg et al., arXiv:2010.12965 (2020) 
[2] A. Eckardt, Phys. Mod. Phys. 89, 311 (2017)
[3] C. Schweizer et al., Nat. Phys. 15, 1168-1173 (2019)
[4] K. Wintersperger et al., Nature Physics 16, 1058-1063 (2020)

## Date

2021-03-03

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [x] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI)
- [x] A reminder email (-4 hours)
- [x] Relay to the speaker the video link and request approval of the recording publication.
- [ ] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by akhmerov** [comment]
@greplova the bot is now ready to publish the videos, so once you reply with timestamps, it should all be good.

**Comment by greplova** [comment]
the speaker approves publishing the recording. start 00:00:02, end 01:12:01
