### ISSUE TITLE
Checklist for LRC by Andy Mackenzie on 03-31-2021

### ISSUE THREAD

**Issue by adelatorreduran** [virtualscienceforum/virtualscienceforum#317]
## Speaker name

Andrew Mackenzie

## Speaker affiliation

Max Planck Institute for Chemical Physics of Solids

## Title

Benefits of good old-fashioned crystalline perfection - new physics in ultra pure delafossite metals

## Abstract

The delafossites are a series of layered compounds with triangular lattices similar to that of NaCoO2 but with a different stacking sequence along the c axis.  They are host to intriguing magnetic insulators and semimetals, as well as metals such as PdCoO2, PtCoO2, PdCrO2 and PdRhO2.  The properties of these metals are remarkable.  Although they are strongly two-dimensional, their room temperature electrical conductivity is higher per carrier than that of any elemental metal, and PdCoO2 crystals can have a low temperature resistivity of only a few nΩcm, corresponding to mean free paths of tens of microns.  I will describe recent experiments from my group in which we have established that the huge mean free paths result from extraordinarily low defect densities in the conducting planes of as-grown crystals, and give examples of new mesoscopic physics that can be observed as a result.  If time permits I will also discuss intriguing bulk and surface states that can be observed with extremely high resolution in angle resolved photoemission experiments.

## Date

2021-03-31

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [x] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI)
- [x] A reminder email (-4 hours)
- [x] Relay to the speaker the video link and request approval of the recording publication.
- [x] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by adelatorreduran** [comment]
I updated the speaker name. Can you confirm and approve?

**Comment by akhmerov** [comment]
The bot seems to work :)

**Comment by adelatorreduran** [comment]
the speaker approves publishing the recording. start 00:00:00, end 01:23:34
