### ISSUE TITLE
Checklist for LRC by Michael Sentef on 2021-04-28

### ISSUE THREAD

**Issue by adelatorreduran** [virtualscienceforum/virtualscienceforum#343]
## Speaker name

Michael Sentef

## Speaker affiliation

Max Planck Institute for the Structure and Dynamics of Matter

## Title

Cavity quantum materials

## Abstract

Recent years have seen tremendous progress in utilizing ultrafast light-matter interaction to control the macroscopic properties of quantum materials [1]. Many of the most intriguing effects are based on nonthermal pathways, with the material (quantum many-body system) being driven away from its thermal equilibrium by strong laser pulses. While this has deepened our understanding of quantum matter far from equilibrium and enabled us to build bridges to other fields (quantum simulators, Floquet states of matter, (pre)thermalization, …), there are a number of challenges: (i) the need for strong lasers, (ii) heating, (iii) short lifetime of light-induced states.

This has motivated an emergent community of researchers to search for new directions that draw inspiration from the discoveries in ultrafast materials science and combine them with expertise gleaned from quantum optics, cavity QED, polaritonic chemistry, and nanoplasmonics, creating the new field of "cavity quantum materials“. 

In this Colloquium, I will provide a personal perspective on this new field and highlight a few of our recent works. Specifically, I will discuss the quantum-to-classical crossover of Floquet engineering in correlated systems and show how a many-photon classical coherent state can be replaced by a few-photon number state, provided that one can reach the regime of sufficiently strong light-matter coupling in a cavity [2]. I will then show how the quantum geometry of wavefunctions impacts their light-matter coupling, and how we envision this to be a key ingredient for future light-matter-based engineering of flat-band (Moiré) materials [3]. 

[1] A. de la Torre, D. M. Kennes, M. Claassen, S. Gerber, J. W. McIver, M. A. Sentef, Nonthermal pathways to ultrafast control in quantum materials, https://arxiv.org/abs/2103.14888
[2] M. A. Sentef, J. Li, F. Künzel, M. Eckstein, Quantum to classical crossover of Floquet engineering in correlated quantum systems, Phys. Rev. Research 2, 033033 (2020)
[3] G. E. Topp, C. J. Eckhardt, D. M. Kennes, M. A. Sentef, P. Törmä, Light-matter coupling and quantum geometry in moiré materials, https://arxiv.org/abs/2103.04967

## Date

2021-04-28

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [x] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [x] A reminder email (-4 hours)
- [x] Relay to the speaker the video link and request approval of the recording publication.
- [x] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by greplova** [comment]
I think I will just Tweet for now not to further the delay and can add some nice pic to the next tweet.

**Comment by akhmerov** [comment]
@adelatorreduran, I see

> Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.

Is still not checked. Can you please confirm that the speaker has the login link?

**Comment by adelatorreduran** [comment]
Checked. He did have it
