### ISSUE TITLE
Checklist for LRC by Andreas Wallraff on April 14th 2021

### ISSUE THREAD

**Issue by everthemore** [virtualscienceforum/virtualscienceforum#345]
## Speaker name
Andreas Wallraff

## Speaker affiliation
ETH Zurich

## Title

Microwave Networks for Solid State Quantum Information Processors

## Abstract

Quantum computing is a radically new approach to processing information. It is one of the approaches which has the potential to address the ever-growing need of society, industry and research for computing power. At ETH Zurich, we have designed, realized and tested a first data link which allows superconducting-circuit-based quantum processors located in different systems to directly exchange quantum information [1]. This link, for a quantum computer, takes the role of a network transferring data between computing nodes located in a high-performance computing data center. However, unlike its conventional counterparts, our data link is operated at ultra-low temperatures, close to the absolute zero. This allows our quantum data link to directly connect to quantum processors operating at the same temperature [2]. The system we have constructed is a first of its kind in the world and could play an important role in growing the power of quantum computers in the future.

[1] P. Magnard et al., Phys. Rev. Lett. 125, 260502 (2020)
[2] P. Kurpiers et al., Nature 558, 264-267 (2018)

## Date

2021-04-14

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [x] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [x] A reminder email (-4 hours)
- [x] Relay to the speaker the video link and request approval of the recording publication.
- [x] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by akhmerov** [comment]
I've changed the tentative titles to TBA for now.

**Comment by everthemore** [comment]
cover image
![PRL_FrontImage](https://user-images.githubusercontent.com/1933169/113196133-7195ea80-9263-11eb-97f7-0d028beb080c.png)

**Comment by everthemore** [comment]
the speaker approves publishing the recording. start 00:00:00, end 01:19:53
