### ISSUE TITLE
Checklist for LRC by Giuseppe Carleo on May 26

### ISSUE THREAD

**Issue by sentefmi** [virtualscienceforum/virtualscienceforum#357]
## Title

*TBA*

## Abstract

*TBA*

## Date

2021-05-28

## Checklist

- [ ] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [ ] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [ ] Check if the speaker wants to join earlier for an informal chat
  - [ ] Check if they do
- [ ] Ask the speaker for a cover image 
  - [ ] if an image is provided, comment with "cover image" as text and attach the image
- [ ] email announcement to all who signed up for updates (-2 weeks)
- [ ] twitter announcement (-2 weeks)
- [ ] reminder twitter announcement (-2 days)
- [ ] assign the roles (moderator/backup) (-2 days)
- [ ] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [ ] A reminder email (-4 hours)
- [ ] Start the LRC Zoom meeting using your VSF Zoom account
- [ ] Relay to the speaker the video link and request approval of the recording publication.
- [ ] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by akhmerov** [comment]
@sentefmi, the LRC is scheduled for May 28th (Friday) instead of 26th (Wednesday). Which one is correct?

**Comment by akhmerov** [comment]
OK, the date is fixed everywhere.

**Comment by sentefmi** [comment]
cover image![image](https://user-images.githubusercontent.com/1454756/118795313-bff65b80-b89a-11eb-8532-20d1d45d9a37.jpeg)

**Comment by akhmerov** [comment]
Ping @greplova for twitter reminder; ping @sentefmi for sharing the link (you'll need zoom account access, but I now sent you an invite).

**Comment by sentefmi** [comment]
> Ping @greplova for twitter reminder; ping @sentefmi for sharing the link (you'll need zoom account access, but I now sent you an invite).

I created my VSF Zoom account. How do I access/share the LRC speaker link?

**Comment by akhmerov** [comment]
I still see "waiting for activation" in your account details. Afterwards you should 

- open the meeting list [here](https://virtualscienceforum-org.zoom.us/user/iJFotmmLRgOHJrTe9MKHRA/meeting#/upcoming) (also accessible via admin → users → VSF user → meetings → upcoming)
- open the relevant meeting
- scroll down to registrations click "view" link
- open the last page (the speaker's registration is chronologically first)
- click "copy" and copy the join link.

**Comment by sentefmi** [comment]
OK - done!

**Comment by sentefmi** [comment]
the speaker approves publishing the recording. start 00:00:04, end 01:05:19
