### ISSUE TITLE
Checklist for LRC by Jon Simon on May 12

### ISSUE THREAD

**Issue by babaks77** [virtualscienceforum/virtualscienceforum#359]
## Title

*TBA*

## Abstract

*TBA*

## Date

2021-05-12

## Checklist

- [ ] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [ ] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [ ] Check if the speaker wants to join earlier for an informal chat
  - [ ] Check if they do
- [ ] Ask the speaker for a cover image 
  - [ ] if an image is provided, comment with "cover image" as text and attach the image
- [ ] email announcement to all who signed up for updates (-2 weeks)
- [ ] twitter announcement (-2 weeks)
- [ ] reminder twitter announcement (-2 days)
- [ ] assign the roles (moderator/backup) (-2 days)
- [ ] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [ ] A reminder email (-4 hours)
- [ ] Start the LRC Zoom meeting using your VSF Zoom account
- [ ] Relay to the speaker the video link and request approval of the recording publication.
- [ ] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by babaks77** [comment]
cover image![image](https://user-images.githubusercontent.com/35002137/116799245-a1841800-aac5-11eb-8637-3cc3c7f86f22.jpeg)

**Comment by greplova** [comment]
@babaks77 ping on the recording permission and publication
