### ISSUE TITLE
Checklist for LRC by Prineha Narang on June 9

### ISSUE THREAD

**Issue by sentefmi** [virtualscienceforum/virtualscienceforum#377]
## Speaker name

Prineha Narang

## Speaker affiliation

Harvard University

## Title

Predicting and Controlling Scalable Quantum Systems

## Abstract

Quantum matter hosts spectacular excited-state and nonequilibrium effects, but many of these phenomena remain challenging to control and, consequently, technologically underexplored. My group’s research, therefore, focuses on how quantum systems behave, particularly away from equilibrium, and how we can harness these effects. By creating predictive theoretical and computational approaches to study dynamics, decoherence and correlations in quantum matter, our work could enable technologies that are inherently more powerful than their classical counterparts ranging from scalable quantum information processing and networks, to ultra-high efficiency optoelectronic and energy conversion systems (1). In this talk, I will present work from my research group on describing, from first principles, the microscopic dynamics, decoherence and optically-excited collective phenomena in quantum matter at finite temperature to quantitatively link predictions with 3D atomic-scale imaging and quantum spectroscopy. Capturing these dynamics poses unique theoretical and computational challenges. The simultaneous contribution of processes that occur on many time and length-scales have remained elusive for state-of-the-art calculations and model Hamiltonian approaches alike, necessitating the development of new methods in computational physics (2–4). I will show selected examples of our approach in ab initio design of active defects in quantum materials (5–7), and control of collective phenomena to link these active defects (8–10). Finally, I will discuss ideas in directly emulating quantum information systems, particularly addressing the issues of model abstraction and scalability, and present an outlook on various co-design strategies with algorithms efforts underway.

1.	Head-Marsden, K., Flick, J., Ciccarino, C. J. & Narang, P. Quantum Information and Algorithms for Correlated Quantum Matter. Chem. Rev. (2020) doi:10.1021/acs.chemrev.0c00620.
2.	Rivera, N., Flick, J. & Narang, P. Variational Theory of Nonrelativistic Quantum Electrodynamics. Phys. Rev. Lett. 122, 193603 (2019).
3.	Flick, J., Rivera, N. & Narang, P. Strong light-matter coupling in quantum chemistry and quantum photonics. Nanophotonics 7, 1479–1501 (2018).
4.	Flick, J. & Narang, P. Cavity-Correlated Electron-Nuclear Dynamics from First Principles. Physical Review Letters vol. 121 (2018).
5.	Narang, P., Ciccarino, C. J., Flick, J. & Englund, D. Quantum Materials with Atomic Precision: Artificial Atoms in Solids: Ab Initio Design, Control, and Integration of Single Photon Emitters in Artificial Quantum Materials. Adv. Funct. Mater. 29, 1904557 (2019).
6.	Hayee, F. et al. Revealing multiple classes of stable quantum emitters in hexagonal boron nitride with correlated optical and electron microscopy. Nat. Mater. 19, 534–539 (2020).
7.	Ciccarino, C. J. et al. Strong spin–orbit quenching via the product Jahn–Teller effect in neutral group IV qubits in diamond. npj Quantum Materials 5, 75 (2020).
8.	Neuman, T., Wang, D. S. & Narang, P. Nanomagnonic Cavities for Strong Spin-Magnon Coupling and Magnon-Mediated Spin-Spin Interactions. Phys. Rev. Lett. 125, 247702 (2020).
9.	Wang, D. S., Neuman, T. & Narang, P. Dipole-coupled emitters as deterministic entangled photon-pair sources. Phys. Rev. Research 2, 043328 (2020).
10.	Neuman, T. et al. A Phononic Bus for Coherent Interfaces Between a Superconducting Quantum Processor, Spin Memory, and Photonic Quantum Networks. arXiv [quant-ph] (2020).

## Date

2021-06-09

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [ ] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] Ask the speaker for a cover image 
  - [x] if an image is provided, comment with "cover image" as text and attach the image
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [x] A reminder email (-4 hours)
- [x] Start the LRC Zoom meeting using your VSF Zoom account
- [x] Relay to the speaker the video link and request approval of the recording publication.
- [x] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by akhmerov** [comment]
@sentefmi please update the checklist (everything is empty :( )

**Comment by sentefmi** [comment]
> @sentefmi please update the checklist (everything is empty :( )

I am on it

**Comment by sentefmi** [comment]
cover image
![FigforLongRange_PNarang_Share](https://user-images.githubusercontent.com/1454756/120817115-b4b95600-c551-11eb-866d-01246308d847.jpg)

**Comment by sentefmi** [comment]
@greplova image source for cover image is
Chem. Rev. 2021, 121, 5, 3061–3120
https://pubs.acs.org/doi/abs/10.1021/acs.chemrev.0c00620#

**Comment by greplova** [comment]
@sentefmi ping on the recording permission and publication

**Comment by vfatemi** [comment]
@sentefmi Can you follow up with Prineha regarding permission to publish the recording.

**Comment by sentefmi** [comment]
On it

**Comment by sentefmi** [comment]
the speaker approves publishing the recording. start 00:00:04, end 01:07:49
