### ISSUE TITLE
Checklist for LRC by Sebastian Huber on 2021-06-23

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#382]
## Speaker name

Sebastian Huber

## Speaker affiliation

ETH Zurich

## Title

Topological Mechanics

## Abstract

Topological band theory provides us with a powerful design-principle for metamaterials that control how waves propagate in space. These metamaterials are ideal to investigate novel phenomena difficult to observe in other platforms. In particular, I will present how artificial gauge fields lead to the appearance of chiral Landau levels in neutral Weyl systems and crystalline symmetries to novel fragile topological states in an acoustic super-structure.

## Date

2021-06-23

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [ ] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] Ask the speaker for a cover image 
  - [x] if an image is provided, comment with "cover image" as text and attach the image
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [x] A reminder email (-4 hours)
- [x] Start the LRC Zoom meeting using your VSF Zoom account
- [x] Relay to the speaker the video link and request approval of the recording publication.
- [ ] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by akhmerov** [comment]
Ping @greplova please update the title/abstract if you have them.

**Comment by greplova** [comment]
Not yet received - reminders has been sent

**Comment by greplova** [comment]
cover image
![D9DED508-54ED-4019-8DCE-BFCEEDEC1A44_1_105_c jpeg](https://user-images.githubusercontent.com/31961952/121883554-29d71900-cd12-11eb-8618-45a93b2eb89d.jpg)

**Comment by greplova** [comment]
@greplova confirm recording permissions

**Comment by greplova** [comment]
the speaker approves publishing the recording. start 00:00:03, end 01:07:34
