### ISSUE TITLE
Checklist for LRC by Andrea Caviglia on 2021-09-15

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#383]
## Speaker name

Andrea Caviglia

## Speaker affiliation

Delft University of Technology

## Title

Ultrafast control of magnetic interactions via light-driven phonons

## Abstract

Resonant ultrafast excitation of infrared-active phonons is a powerful technique with which to control the electronic properties of materials that leads to remarkable phenomena such as light-induced superconductivity, switching of ferroelectric polarization and ultrafast insulator-to-metal transitions. We will discuss how light-driven phonons can be utilized to coherently manipulate macroscopic magnetic states. Intense mid-infrared electric field pulses tuned to resonance with a phonon mode of the archetypical antiferromagnet DyFeO3 induce ultrafast and long-living changes of the fundamental exchange interaction between rare-earth orbitals and transition metal spins. Non-thermal lattice control of the magnetic exchange, which defines the stability of the macroscopic magnetic state, allows us to perform picosecond coherent switching between competing antiferromagnetic and weakly ferromagnetic spin orders. In this talk, the potential of resonant phonon excitation for the manipulation of ferroic order on ultrafast timescales will be emphasized.

## Date

2021-09-15

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [ ] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] Ask the speaker for a cover image 
  - [x] if an image is provided, comment with "cover image" as text and attach the image
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [x] A reminder email (-4 hours)
- [x] Start the LRC Zoom meeting using your VSF Zoom account
- [x] Relay to the speaker the video link and request approval of the recording publication.
- [ ] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by akhmerov** [comment]
cover image

![cover](https://user-images.githubusercontent.com/2069677/123509877-5b3bd700-d678-11eb-89f3-f336f937118e.jpg)

**Comment by babaks77** [comment]
Not sure how this issue needs to be updated through the bot for the new date. From today's meeting we have an action point:
  - [ ] confirm move to Sept 15
  - [ ] update the configuration

**Comment by akhmerov** [comment]
the speaker approves publishing the recording. start 00:01:03, end 00:47:04
