### ISSUE TITLE
Checklist for LRC by Richard Kueng on September 1st 2021

### ISSUE THREAD

**Issue by everthemore** [virtualscienceforum/virtualscienceforum#408]
## Speaker name
Richard Kueng

## Speaker affiliation
Johannes Kepler University, Linz, Austria

## Title

Provably efficient machine learning for quantum many-body problems

## Abstract

Classical machine learning (ML) provides a potentially powerful approach to solving challenging problems in quantum physics and chemistry. However, the advantages of ML over more traditional methods have not been firmly established. We prove that classical ML algorithms can efficiently predict ground state properties of a physical system, after learning from data obtained by measuring related systems. We also prove that classical ML algorithms can efficiently classify a wide range of quantum phases of matter. Our arguments are based on the concept of a classical shadow, a succinct classical description of a quantum state that can be constructed in feasible quantum experiments and be used to predict many properties of the state.

This is joint work with Robert Huang (Caltech), Giacomo Torlai (AWS), Victor Albert (University of Maryland) and John Preskill (Caltech+AWS).

## Date

2021-09-01

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [x] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] Ask the speaker for a cover image 
  - [x] if an image is provided, comment with "cover image" as text and attach the image
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [x] A reminder email (-4 hours)
- [x] Start the LRC Zoom meeting using your VSF Zoom account
- [x] Relay to the speaker the video link and request approval of the recording publication.
- [x] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by akhmerov** [comment]
@everthemore it's time to announce this, do you have the image?

**Comment by everthemore** [comment]
cover image
[kueng-thumbnail.pdf](https://github.com/virtualscienceforum/virtualscienceforum/files/7030592/kueng-thumbnail.pdf)

**Comment by everthemore** [comment]
the speaker approves publishing the recording. start 00:00:00, end 01:09:52

**Comment by akhmerov** [comment]
The bot will close the issue; @everthemore we also discussed publishing the slides; can you upload the PDF here for the future use?

**Comment by everthemore** [comment]
[kueng-ML-nopauses.pdf](https://github.com/virtualscienceforum/virtualscienceforum/files/7136688/kueng-ML-nopauses.pdf)
