### ISSUE TITLE
Checklist for LRC by Cui-Zu Chang on Sept. 29

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#413]
## Speaker name
Cui-Zu Chang
## Speaker affiliation
Pennsylvania State University
## Title

Quantum Anomalous Hall Effect in the Magnetic Topological Insulator Thin Films

## Abstract
The quantum anomalous Hall (QAH) effect can be considered as the quantum Hall (QH) effect without an external magnetic field, which can be realized by time-reversal symmetry breaking in a topologically non-trivial system [1, 2]. A QAH system carries spin-polarized dissipationless chiral edge transport channels without the need for external energy input, hence may have a huge impact on future electronic and spintronic device applications for ultralow-power consumption. The many decades' quest for the experimental realization of the QAH phenomenon became a possibility in 2006 with the discovery of topological insulators (TIs). In 2013, the QAH effect was observed in thin films of Cr-doped TI for the first time [3]. Two years later in a near-ideal system, V-doped TI, contrary to the negative prediction from first principle calculations [2], a high-precision QAH quantization with more robust magnetization and a perfectly dissipationless chiral current flow was demonstrated [4]. In this talk, I will introduce the route to the experimental observation of the QAH effect in the aforementioned two systems [3, 4], and also talk about our recent progress on the high Chern number QAH effect in magnetic TI multilayers [5].  
 [1] Haldane, Phys. Rev. Lett. 61, 2015 (1988).  
 [2] Yu et al, Science 329, 61 (2010).  
 [3] Chang et al, Science 340, 167(2013).  
 [4] Chang et al, Nat. Mater. 14, 473(2015).  
 [5] Zhao et al, Nature 588, 419 (2020).

## Date

2021-09-29

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [ ] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] Ask the speaker for a cover image 
  - [x] if an image is provided, comment with "cover image" as text and attach the image
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [x] A reminder email (-4 hours)
- [x] Start the LRC Zoom meeting using your VSF Zoom account
- [x] Relay to the speaker the video link and request approval of the recording publication.
- [x] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by akhmerov** [comment]
@vfatemi did you ask about a cover image?

**Comment by vfatemi** [comment]
cover image
![CZZhang_image](https://user-images.githubusercontent.com/61348213/134691633-bc6f718d-59fe-4768-85ee-2533bebddea3.png)

**Comment by vfatemi** [comment]
the speaker approves publishing the recording. start 00:00:00, end 01:06:12
