### ISSUE TITLE
Checklist for LRC by Atac Imamoglu on Oct 13

### ISSUE THREAD

**Issue by sentefmi** [virtualscienceforum/virtualscienceforum#414]
## Speaker name

Atac Imamoglu

## Speaker affiliation

ETH Zurich

## Title

Strongly correlated electrons in atomically thin semiconductors

## Abstract

In this talk, I will describe recent experiments in atomically-thin transition metal dichalcogenides (TMDs) where Coulomb interactions between electrons dominate over their kinetic energy. Our measurements provide a direct evidence that the electrons at densities < 3 · 10^11 cm-2 in a pristine MoSe2 monolayer form a Wigner crystal even at B = 0. This is revealed by our low-temperature (T = 80 mK) magneto-optical spectroscopy experiments that utilize a newly developed technique allowing to unequivocally detect charge order in an electronic Mott-insulator state. This method relies on the modification of excitonic band structure arising due to the periodic potential experienced by the excitons interacting with a crystalline electronic lattice. Under such conditions, optically-inactive exciton states with finite momentum matching the reciprocal Wigner lattice vector k = k­W get Bragg scattered back to the light cone, where they hybridize with the zero-momentum bright exciton states. This leads to emergence of a new, umklapp peak in the optical spectrum heralding the presence of periodically-ordered electronic lattice.

## Date

2021-10-13

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [ ] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] Ask the speaker for a cover image 
  - [x] if an image is provided, comment with "cover image" as text and attach the image
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [ ] A reminder email (-4 hours)
- [ ] Start the LRC Zoom meeting using your VSF Zoom account
- [ ] Relay to the speaker the video link and request approval of the recording publication.
- [ ] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by sentefmi** [comment]
cover image 
![WC_cover_illustration](https://user-images.githubusercontent.com/1454756/130321354-c31eecda-3026-4977-ba35-d9d26564202a.jpg)

**Comment by sentefmi** [comment]
Just a reminder that we need a chair for the talk, since I am going to be on vacation on that day

**Comment by akhmerov** [comment]
I'll be around.

**Comment by sentefmi** [comment]
@greplova can you do the twitter announcement?

**Comment by akhmerov** [comment]
> Just a reminder that we need a chair for the talk, since I am going to be on vacation on that day

Happy to chair

**Comment by greplova** [comment]
will do @sentefmi 
just tweeted reminder for tonight, so will send this one approx tomorrow not to create confusion about the order

**Comment by akhmerov** [comment]
The speaker approves publishing the recording. start 00:01:27 end 00:57:32, start 01:02:58 end 01:11:24

**Comment by akhmerov** [comment]
The speaker approves publishing the recording. start 00:01:27 end 00:57:32, start 01:02:58 end 01:11:24
