### ISSUE TITLE
Checklist for LRC by Corentin Coulais on 2021-12-01

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#430]
## Speaker name

Corentin Coulais

## Speaker affiliation

University of Amsterdam

## Title

The Non-Hermitian physics of odd Robotic Matter

## Abstract

Controlling how waves propagate, attenuate and amplify in simple, scalable geometric structures is a daunting challenge for science and technology. In this talk, I will discuss how odd matter—in which microscopic interactions are asymmetric and non-conservative—can be used to steer mechanical waves in unprecedented ways. Combining experiments on mechanical lattices of distributed robots with wave physics and continuum and topological mechanics, I will discuss the emergence of the non-Hermitian skin effect, of non-Hermitian topological waves and of one-way solitons. I will further show how these odd waves can be used to induce locomotion and unusual responses to impacts and hence pave the way towards a novel generation of materials with animate properties.

References:

1. Active impact and locomotion in robotic matter with nonlinear work cycles  
   Brandenbourger M., Scheibner C., Veenstra J., Vitelli V., Coulais C., [arXiv:2108.08837](https://arxiv.org/abs/2108.08837)
2. Topology and broken hermiticity  
   Coulais C., Fleury R. and van Wezel J., [Nat. Phys. 17, 9–13 (2021)](https://doi.org/10.1038/s41567-020-01093-z)
3. Observation of non-Hermitian topology and its bulk-edge correspondence in an active mechanical metamaterial  
   Ghatak A., Brandenbourger M., van Wezel J. and Coulais C., [Proc. Natl. Ac. Sc. U.S.A. 117 (47) 29561 (2020)](https://doi.org/10.1073/pnas.2010580117)
4. Non-reciprocal robotic metamaterials  
   Brandenbourger M., Locsin X., Lerner E. and Coulais C., [Nat. Commun., 10, 4608 (2019)](https://doi.org/10.1038/s41467-019-12599-3)

## Date

2021-12-01

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [ ] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] Ask the speaker for a cover image 
  - [x] if an image is provided, comment with "cover image" as text and attach the image
- [ ] email announcement to all who signed up for updates (-2 weeks)
- [ ] twitter announcement (-2 weeks)
- [ ] reminder twitter announcement (-2 days)
- [ ] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [ ] A reminder email (-4 hours)
- [ ] Start the LRC Zoom meeting using your VSF Zoom account
- [ ] Relay to the speaker the video link and request approval of the recording publication.
- [ ] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by akhmerov** [comment]
Since this is so far in the future, I'll hold off approving until we have the title and abstract.

**Comment by akhmerov** [comment]
Update: we realized that 24th is the day before thanksgiving, and hence I'm proposing to postpone by 2 weeks.

**Comment by akhmerov** [comment]
Two images to choose from:

![image002](https://user-images.githubusercontent.com/2069677/142497515-79052486-b192-40b4-87ac-f43de8286ec9.gif)

![image001 (1)](https://user-images.githubusercontent.com/2069677/142497556-5c53a00e-fa6e-47a5-9bfa-d8781d238998.png)

**Comment by akhmerov** [comment]
The speaker approves publishing of the recording. Start 00:00:42 end 01:10:07
