### ISSUE TITLE
Checklist for LRC by Nicole Yunger Halpern on October 27

### ISSUE THREAD

**Issue by sentefmi** [virtualscienceforum/virtualscienceforum#431]
## Speaker name
Nicole Yunger Halpern

## Speaker affiliation
National Institute of Standards and Technology (NIST), Joint Institute for Quantum Information and Computer Science (QuICS) University of Maryland

## Title

MBL-mobile: Many-body-localized engine

## Abstract

Many-body-localized (MBL) systems do not thermalize under their intrinsic dynamics. The athermality of MBL, we propose, can be harnessed for thermodynamic tasks. We illustrate this ability by formulating an Otto engine cycle for a quantum many-body system. The system is ramped between a strongly localized MBL regime and a thermal (or weakly localized) regime. The difference between the energy-level correlations of MBL systems and of thermal systems enables mesoscale engines to run in parallel in the thermodynamic limit, enhances the engine’s reliability, and suppresses worst-case trials. We estimate analytically and calculate numerically the engine’s efficiency and per-cycle power. The efficiency mirrors the efficiency of the conventional thermodynamic Otto engine. This work introduces a thermodynamic lens onto MBL, which, having been studied much recently, can now be leveraged in thermodynamic tasks.

Serious reference: NYH, White, Gopalakrishnan, and Refael, Phys. Rev. B 99, 024203 (2019) https://dx.doi.org/10.1103/PhysRevB.99.024203.

Fun reference: NYH, “Quantum Steampunk,” Sci. Am. (May 2020) https://www.scientificamerican.com/article/quantum-steampunk-19th-century-science-meets-technology-of-today/ 

## Date

2021-10-27

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [ ] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] Ask the speaker for a cover image 
  - [x] if an image is provided, comment with "cover image" as text and attach the image
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [x] A reminder email (-4 hours)
- [x] Start the LRC Zoom meeting using your VSF Zoom account
- [x] Relay to the speaker the video link and request approval of the recording publication.
- [x] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by sentefmi** [comment]
cover image
![MBL-mobile image](https://user-images.githubusercontent.com/1454756/135035265-f62957fd-8d9a-4651-a97f-57ec88acbe3d.jpg)

**Comment by sentefmi** [comment]
@greplova 
"Cover image is credited to Scientific American (https://www.scientificamerican.com/article/quantum-steampunk-19th-century-science-meets-technology-of-today/). If you'd like to tag me @nicoleyh11, I can retweet the tweet."

**Comment by sentefmi** [comment]
the speaker approves publishing the recording. start 00:00:06, end 01:01:34
