### ISSUE TITLE
Checklist for LRC by David Goldhaber-Gordon on November 10, 2021

### ISSUE THREAD

**Issue by vfatemi** [virtualscienceforum/virtualscienceforum#436]
## Speaker name
David Goldhaber-Gordon

## Speaker affiliation
Stanford University

## Title

Can a solid-state quantum simulator help us understand materials?

## Abstract

When we speak of a quantum computer today, we usually mean one that can run any algorithm. But the idea of using a quantum-based computer to simulate aspects of our quantum world goes back at least to Feynman in the early 1980s. Effective model Hamiltonians are central to condensed matter physics, as they can capture the essence of material properties while avoiding the full complexity of actual materials. But even those model Hamiltonians can be intractable to treat on classical computers. Very perfect realizations of model Hamiltonians relevant to materials can now be built with ensembles of cold atoms or with nanopatterned solid state systems similar to those used to make qubits. I will compare new experimental results to cutting-edge classical computation, and then ask: What happens when we (soon!) get our wish and achieve a "quantum simulator" that can describe certain interesting Hamiltonians with power beyond the best classical computers and algorithms?

## Date

2021-11-10

## Checklist

- [x] update the [LRC speakers](https://github.com/virtualscienceforum/virtualscienceforum/wiki/LRC-Speakers) wiki page
- [ ] update the [researchseminars.org](https://researchseminars.org/seminar/VSFLRC) listing (need to get link or ask Babak)
- [x] Check if the speaker wants to join earlier for an informal chat
  - [x] Check if they do
- [x] Ask the speaker for a cover image 
  - [ ] if an image is provided, comment with "cover image" as text and attach the image
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] reminder twitter announcement (-2 days)
- [x] assign the roles (moderator/backup) (-2 days)
- [x] Email the speaker their login link (access it via Zoom UI). Ask the speaker to check their screen resolution is max 1080p.
- [x] A reminder email (-4 hours)
- [x] Start the LRC Zoom meeting using your VSF Zoom account
- [x] Relay to the speaker the video link and request approval of the recording publication.
- [x] respond with "the speaker approves publishing the recording. start HH:MM:SS, end HH:MM:SS"

**Comment by greplova** [comment]
> Seems no cover image.

okay I'll tweet without this time

**Comment by vfatemi** [comment]
the speaker approves publishing the recording. start 00:00:00, end 01:08:31
