### ISSUE TITLE
VSF Long Range Colloquium TODO

### ISSUE THREAD

**Issue by xabomon** [virtualscienceforum/virtualscienceforum#50]
- [x] Decide on seminar scope for the first series
- [x]  Agree on the number of seminars, period of them and time-slot
- [x] Search for speakers

A time-frame of a week should be enough to complete this actions points.

**Comment by akamra47** [comment]
How about the following?

1. "Condensed matter physics or Quantum physics" as the scope. 
2. One seminar every two weeks, 1 hour seminar (45 min talk plus questions), 4pm European time on Thursday.
3.  Search can begin when the above two questions have been answered.

**Comment by xabomon** [comment]
Seminar will take place on Wednesday at 7:30 pm (CET) starting April, 15

**Comment by xabomon** [comment]
We seem to have checked all the TODOs in this Issue. I'm going to go ahead and close it.
