### ISSUE TITLE
long range colloquium 29.04 checklist

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#66]
- [x] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] software test with the speaker (up to -1 day)
- [x] reminder twitter announcement (-3 days)
- [x] assign the roles (moderator/recording)
- [x] ~~email registered participants (-1 day)~~
- [x] recheck capacity, scale up the room (-1 day)
- [x] final email (-2 hours)
- [x] close the registration and update the page (right after the talk)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording (+2 days)

**Comment by akhmerov** [comment]
- @vfatemi will be moderating
- Following a discussion, we'll only send an announcement 1-2 hours before the event.
