### ISSUE TITLE
Long range colloquium 13.05 checklist

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#78]
- [x] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] software test with the speaker (up to -1 day)
- [x] reminder twitter announcement (-3 days)
- [x] assign the roles (moderator/recording)
- [x] recheck capacity, scale up the room (-1 day)
- [x] close the registration and update the page (right after the talk)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording (+2 days)

**Comment by akhmerov** [comment]
@greplova would you like to do the twitter announcement?

@babaks77 you're the best candidate for the speaker software test and for moderation, is that OK?

I'll email the announcement.

**Comment by greplova** [comment]
@akhmerov thank you for the reminder. Will do!

**Comment by babaks77** [comment]
@akhmerov yes, I'll do the speaker equipment test and moderation.

**Comment by babaks77** [comment]
I corrected the date in the title of the issue (13.04 to 13.05)

**Comment by akhmerov** [comment]
@babaks77 we also need to embed the video on the website.

**Comment by babaks77** [comment]
Thanks @akhmerov, I forgot to do that.
