### ISSUE TITLE
Colloquium checklist for 27.05

### ISSUE THREAD

**Issue by babaks77** [virtualscienceforum/virtualscienceforum#82]
- [x] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] software test with the speaker (up to -1 day)
- [x] creating polls for the talk (up to -1 day)
- [x] reminder twitter announcement (-3 days)
- [x] assign the roles (moderator/recording)
- [x] recheck capacity, scale up the room (-1 day)
- [x] close the registration and update the page (right after the talk)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording (+2 days)

**Comment by akamra47** [comment]
Nicola would like to ask questions to the audience, which can be done via polls. Hence, I took the liberty of adding "creating polls for the talk" to the list above.

**Comment by akhmerov** [comment]
Great idea. @babaks77 is the only one with the account access, so if she sends us the list of questions and answer options for the polls, @babaks77 can add them to the meeting.

**Comment by akamra47** [comment]
I have asked her for the questions and will communicate them as soon as I have them.
