### ISSUE TITLE
Checklist for long range colloquium 2020-10-06

### ISSUE THREAD

**Issue by akhmerov** [virtualscienceforum/virtualscienceforum#94]
- [x] registration open (-2 weeks)
- [x] page updated (-2 weeks)
- [x] email announcement to all who signed up for updates (-2 weeks)
- [x] twitter announcement (-2 weeks)
- [x] software test with the speaker (up to -1 day)
- [x] creating polls for the talk (up to -1 day)
- [x] reminder twitter announcement (-3 days)
- [x] assign the roles (moderator/recording)
- [x] recheck capacity, scale up the room (-1 day)
- [x] decide about and inform the participants for after colloquium discussion (-1 day)
- [x] close the registration and update the page (right after the talk)
- [x] get the speaker's approval of the recording (+1 day)
- [x] publish the recording on YouTube and embed on webpage (+2 days)

**Comment by akhmerov** [comment]
@greplova did you hear back whether the speaker would like to experiment talking with participants?

**Comment by greplova** [comment]
Wrote an email. No reply so far. Did we converge on the exact format in the end? I just wrote whether he has time for smaller group after-colloquium discussion with selected participants.

**Comment by akhmerov** [comment]
We did, but to start making this happen we need the speaker's agreement in the first place.

**Comment by greplova** [comment]
Speaker is in for the after-colloquium discussion

**Comment by akamra47** [comment]
Can we then make an appropriate registration form and open registration before today's talk? I guess @babaks77 would know.

**Comment by akhmerov** [comment]
Also copying here: let's postpone this until we properly figure out the registration form.

**Comment by babaks77** [comment]
Agreed with a short delay to figure out the question and format.

**Comment by akhmerov** [comment]
Due to https://particlesforjustice.org we are postponing the colloquium by one week.

The updated to do list:

- [ ] Update the schedule on the website
- [ ] Update the zoom meeting
- [ ] Announce on twitter
- [ ] Announce to registered participants

Did I miss anything?

**Comment by greplova** [comment]
I think this is everything. I can take care of the first three.

**Comment by akhmerov** [comment]
Thanks, I'll take care to email the registered participants, but the email body would help.

**Comment by babaks77** [comment]
Here is a draft of email body.

Subject: VSF Long Range Colloquium Rescheduled

Dear *** NAME ***,

Affirming our commitment to the values of human rights and dignity and hoping for a world free of racial bias and discrimination, Klaus Mølmer's VSF Long Range Colloquium scheduled for this Wednesday June 10, 2020 is postponed in support of our colleague's call for Strike for Black Lives: https://www.particlesforjustice.org. The colloquium is rescheduled for Wednesday June 17, 2020 at 1:30pm EST / 7:30pm CET.

In solidarity,
The VSF team

**Comment by akhmerov** [comment]
Here's the updated version:

The Virtual Science Forum aims to give everyone an equal opportunity to take part in scientific discussion. We are committed to the values of human rights and dignity and hope for a world free of racial bias and discrimination. Therefore we are joining our colleagues' call for Strike for Black Lives on June 10th: https://www.particlesforjustice.org. After consultation with the speaker, we rescheduled the VSF Long Range Colloquium by Klaus Mølmer to Wednesday June 17, 2020 1:30pm EST / 7:30pm CEST.

**Comment by akhmerov** [comment]
Zoom offers to notify participants like this, but I'll probably rather send a personalized email.

![image](https://user-images.githubusercontent.com/2069677/84051305-3a420e80-a9af-11ea-9f4f-f7394e9bfde7.png)

**Comment by greplova** [comment]
Zoom for after-colloquium discussion created, speaker registered and informed about the procedure.

**Comment by greplova** [comment]
Speaker approval for publishing on YouTube granted
